language: node_js
node_js:
  - "8.2.1"

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
  - ./bin/make_postman_env.sh

script:
  - overcommit --sign; overcommit --run
  - node_modules/.bin/newman run tests/*.json -e ./postman_env.json
